# Generated by Django 2.0.6 on 2018-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
    ]
