# Generated by Django 2.0.6 on 2018-06-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id_aspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aspirante', models.CharField(max_length=20)),
                ('apellido_aspirante', models.CharField(max_length=20)),
                ('contrasena_aspirante', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=9)),
                ('fechas_nac', models.DateField()),
                ('t_fijo', models.CharField(max_length=10)),
                ('t_movil', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('titulo_pre', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=30)),
                ('f_expedicion', models.DateField()),
                ('municipio', models.CharField(max_length=50)),
                ('lugar_trab', models.CharField(max_length=50)),
                ('programa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emcabezado', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('permisoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('codigo_permiso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('rolPermisoId', models.AutoField(primary_key=True, serialize=False)),
                ('permisoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Permiso')),
                ('rolId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Rol')),
            ],
        ),
       
    ]
