# Generated by Django 2.0.6 on 2018-06-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180622_1958'),
    ]

    
    
