# Generated by Django 2.0.6 on 2018-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180925_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasos',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
