# Generated by Django 2.0.6 on 2018-06-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180622_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=15)),
                ('rol_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Rol')),
            ],
        ),
       
    ]
