# Generated by Django 2.0.6 on 2018-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pasos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='dui',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
