# Generated by Django 2.0.6 on 2018-06-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180622_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario2',
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Usuario2'),
        ),
    ]
