# Generated by Django 2.0.6 on 2018-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180926_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='aceptado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
