# Generated by Django 2.0.6 on 2018-09-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180928_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='formacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='docente',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
