# Generated by Django 2.0.6 on 2018-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180928_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='nombreuser_aspirante',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='usuario',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
