# Generated by Django 2.0.6 on 2018-06-30 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_auto_20180630_2120'),
    ]

    operations = [


        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),

    ]
