# Generated by Django 2.0.6 on 2018-07-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_auto_20180630_2120'),
    ]

    operations = [

    ]
