# Generated by Django 2.0.6 on 2018-07-10 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_auto_20180701_2355'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='rolpermiso',
            name='permisoId',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='rolId',
        ),
        migrations.RemoveField(
            model_name='usuario2',
            name='rol_id',
        ),



        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='RolPermiso',
        ),
        migrations.DeleteModel(
            name='Usuario2',
        ),

    ]
